[tox]
requires =
    tox>=4.2
env_list =
    py3{10,11,12}-django42
    py3{10,11,12,13,14}-django52
    py3{12,13,14}-django60

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314

[testenv]
package = wheel
deps =
    bleach>=6.2.0,<7
    coverage[toml]
    mock
    tinycss2
    django42: django>=4.2,<4.3
    django52: django>=5.2,<5.3
    django60: django>=6.0,<6.1
set_env =
    PYTHONDEVMODE = 1
    PYTHONDONTWRITEBYTECODE=1
commands =
    python \
      -W error::ResourceWarning \
      -W error::DeprecationWarning \
      -W error::PendingDeprecationWarning \
      -m coverage run testproject/manage.py test django_bleach
